### ISSUE TITLE
num_works大于0则报错

### ISSUE THREAD

**Issue by FriendChi** [zkyntu/UnLanedet#24]
[11/20 10:34:27 Ld.utils.events]:  iter: 0       lr: N/A  max_mem: 85M
Traceback (most recent call last):
  File "D:\Kaggle\UnLanedet-main\tools\train_net.py", line 134, in <module>
    invoke_main()  # pragma: no cover
  File "D:\Kaggle\UnLanedet-main\tools\train_net.py", line 123, in invoke_main
    launch(
  File "d:\kaggle\unlanedet-main\unlanedet\engine\lanuch.py", line 81, in launch
    main_func(*args)
  File "D:\Kaggle\UnLanedet-main\tools\train_net.py", line 118, in main
    do_train(args, cfg)
  File "D:\Kaggle\UnLanedet-main\tools\train_net.py", line 103, in do_train
    trainer.train(start_iter, cfg.train.max_iter)
  File "d:\kaggle\unlanedet-main\unlanedet\engine\train_loop.py", line 150, in train
    self.run_step()
  File "d:\kaggle\unlanedet-main\unlanedet\engine\train_loop.py", line 291, in run_step
    data = next(self._data_loader_iter)
  File "d:\kaggle\unlanedet-main\unlanedet\engine\train_loop.py", line 339, in _data_loader_iter
    self._data_loader_iter_obj = IterLoader(dataloader=self.data_loader)
  File "d:\kaggle\unlanedet-main\unlanedet\data\iterload.py", line 4, in __init__
    self.iter_loader = iter(self._dataloader)
  File "F:\Anaconda3\envs\unlanedet\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "F:\Anaconda3\envs\unlanedet\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "F:\Anaconda3\envs\unlanedet\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "F:\Anaconda3\envs\unlanedet\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "F:\Anaconda3\envs\unlanedet\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\Anaconda3\envs\unlanedet\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "F:\Anaconda3\envs\unlanedet\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\Anaconda3\envs\unlanedet\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "F:\Anaconda3\envs\unlanedet\lib\site-packages\torch\multiprocessing\reductions.py", line 192, in reduce_tensor
    raise RuntimeError(
RuntimeError: Cowardly refusing to serialize non-leaf tensor which requires_grad, since autograd does not support crossing process boundaries.  If you just want to transfer the data, call detach() on the tensor before serializing (e.g., putting it on the queue).
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\Anaconda3\envs\unlanedet\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "F:\Anaconda3\envs\unlanedet\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
[W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

在进行clrernet的训练时遇到的，windows10

**Comment by zkyntu** [comment]
I will check this problem later and give you a reply in the afternoon.

**Comment by zkyntu** [comment]
@FriendChi Hi, Could you provide the whole log? My training platform is Linux instead of Windows. I don not know whether the bugs exist on Windows.

**Comment by zkyntu** [comment]
Yes. This problem is caused by Windows. I will add the running platform to the readme. Thanks again!

**Comment by FriendChi** [comment]
OK,thanks for your help.
